WebAssetManagementMvc/WebAssetManagementMvc/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ext.Net.MVC;
using Ext.Net;
using log4net;

namespace WebAssetManagementMvc.Controllers
{
    public class PlanController : Controller
    {
        //
        // GET: /Plan/
        private ILog _log = LogManager.GetLogger(typeof(PlanController).Name);

        public ActionResult Index()
        {
            return View();
        }


        public Ext.Net.MVC.PartialViewResult ShowPlanWindow(string containerId)
        {

            var view = new Ext.Net.MVC.PartialViewResult(containerId, RenderMode.RenderTo);

            return view;
        }

        [HttpGet]
        public ActionResult GetPlan(string name)
        {

            _log.DebugFormat("name: {0}", name);
            var file = Server.MapPath(string.Format("~/Plans/{0}", name));
            if (!System.IO.File.Exists(file))
            {
                throw new System.IO.FileNotFoundException(string.Format("no file path: {0}", file));
            }

            return File(file, "application/pdf");
        }

    }
}

WebAssetManagementMvc/WebAssetManagementMvc/Views/Plan/ShowPlanWindow.cshtml
@{
    var X = Html.X();

    const int WIDTH = 1000;
    const int HEIGHT = 600;

    var loader1 = new ComponentLoader
        {
            Url = Url.Action("GetPlan", "Plan"),
            Mode = LoadMode.Frame,
            LoadMask =
            {
                ShowMask = true
            },
        };
    loader1.Params.Add(new Parameter("name", "FL1.pdf"));
    
    
    var loader2 = new ComponentLoader
        {
            Url = Url.Action("GetPlan", "Plan"),
            Mode = LoadMode.Frame,
            LoadMask =
            {
                ShowMask = true
            },
        };
    loader2.Params.Add(new Parameter("name", "FL2.pdf"));

    var loader3 = new ComponentLoader
        {
            Url = Url.Action("GetPlan", "Plan"),
            Mode = LoadMode.Frame,
            LoadMask =
            {
                ShowMask = true
            },
        };
    loader3.Params.Add(new Parameter("name", "Fl3.pdf"));
    
}



@(X.Window()
        .Title("Plan")
        .CloseAction(CloseAction.Destroy)
        .Width(WIDTH)
        .Height(HEIGHT)
        .Maximizable(true)
        .Icon(Icon.Page)
        .Layout(LayoutType.Border)
        .Items(

        X.TabPanel()
        .Region(Region.Center)
       .ID("TabPanel1")
       .Items(

                X.FormPanel()
                .Title("ชั้นที่ 1")
                .ID("Form1")
                .Frame(true)
                .Width(WIDTH)
                .Height(HEIGHT)
                .BodyPadding(13)
                .Margins("5 5 5 0")
                .Loader(loader1)
                ,

                      /********************* next form *******************************/
                X.FormPanel()
                .Title("ชั้นที่ 2")
                .ID("Form2")
                .Frame(true)
                .Width(WIDTH)
                .Height(HEIGHT)
                .BodyPadding(13)
                .Margins("5 5 5 0")
                .Loader(loader2),
                
                X.FormPanel()
                .Title("ชั้นที่ 3")
                .ID("Form3")
                .Frame(true)
                .Width(WIDTH)
                .Height(HEIGHT)
                .BodyPadding(13)
                .Margins("5 5 5 0")
                .Loader(loader3)
       )//end tab
       )

)