WebAssetManagementMvc/WebAssetManagementMvc/Models/Employee.cs
namespace WebAssetManagementMvc.Models
{
    public class Employee
    {
        public virtual int EmployeeId { get; set; }
        public virtual string EmployeeName { get; set; }
        public virtual string Address { get; set; }
        public virtual string Sex { get; set; }
        public virtual string Username { get; set; }
        public virtual string Password { get; set; }
        //public virtual int PositionId { get; set; }
        public virtual Position Position { get; set; }

        //EMPLOYEE_ID
        //POSITION_ID

        //EMPLOYEE_NAME
        //ADDRESS
        //SEX
        //USERNAME
        //PASSWORD

    }
}

WebAssetManagementMvc/WebAssetManagementMvc/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ext.Net;
using Ext.Net.MVC;
using NHibernate.Linq;
using WebAssetManagementMvc.Messages.Reponses;
using WebAssetManagementMvc.Models;
using log4net;
using Position = WebAssetManagementMvc.Models.Position;

namespace WebAssetManagementMvc.Controllers
{
    public class EmployeeController : Controller
    {
        private ILog _log = LogManager.GetLogger(typeof(EmployeeController).Name);
        private const int NOTIFY_DELAY = 1000;//ms

        public Ext.Net.MVC.PartialViewResult EmployeeList(string containerId)
        {

            var container = X.GetCmp<Container>(containerId);
            container.RemoveAll(true);

            var view = new Ext.Net.MVC.PartialViewResult(containerId, RenderMode.AddTo);

            try
            {
                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Information,
                                     Title = "Loaded",
                                     Html = "Employee list loaded",
                                     AutoHide = true,
                                     HideDelay = NOTIFY_DELAY,
                                 }).Show();


                using (var session = SessionFactory.GetNewSession())
                {

                    var employeeListResponse = session.Query<Employee>()
                        .Select(e => new EmployeeListResponse()
                     {
                         Address = e.Address,
                         EmployeeId = e.EmployeeId,
                         EmployeeName = e.EmployeeName,
                         Password = e.Password,
                         PositionId = e.Position.PositionId,
                         PositionName = e.Position.PositionName,
                         Sex = e.Sex,
                         Username = e.Username,
                     }).ToList();

                    view.Model = employeeListResponse;
                }
            }
            catch (Exception ex)
            {
                _log.Error(ex);
            }

            return view;
        }

        [HttpPost]
        public DirectResult Edit(int id, string field, string oldValue, string newValue, [Bind(Prefix = "object")] Employee employee)
        {
            _log.InfoFormat("employee name: {0}", employee.EmployeeName);
            _log.InfoFormat("id: {0}", id);
            var message = "<b>Property:</b> {0}<br /><b>Field:</b> {1}<br /><b>Old Value:</b> {2}<br /><b>New Value:</b> {3}";
            using (var session = SessionFactory.GetNewSession())
            {

                var employeeFromDb = session.Get<Employee>(id);
                var type = typeof(Employee);

                //set new value
                var propertyToChange = type.GetProperty(field);
                var newValueCorrectType = Convert.ChangeType(newValue, propertyToChange.PropertyType);
                propertyToChange.SetValue(employeeFromDb, newValueCorrectType, null);


                session.Flush();
            }

            // Send Message...
            X.Msg.Notify(new NotificationConfig()
            {
                Title = "Edit Record #" + id.ToString(),
                Html = string.Format(message, id, field, oldValue, newValue),
                Width = 250
            }).Show();

            X.GetCmp<Store>("employeeStore").GetById(id).Commit();

            return this.Direct();
        }

        [HttpGet]
        public Ext.Net.MVC.PartialViewResult AddEmployee(string containerId)
        {
            X.Msg.Notify(new NotificationConfig
                             {
                                 Icon = Icon.Accept,
                                 Title = "Loaded",
                                 Html = "AddEmployee form loaded",
                                 AutoHide = true,
                                 HideDelay = NOTIFY_DELAY,
                             }).Show();

            var container = X.GetCmp<Container>(containerId);
            container.RemoveAll(true);
            AddEmployeeViewModel viewModel;
            using (var session = SessionFactory.GetNewSession())
            {
                viewModel = new AddEmployeeViewModel()
                {
                    Genders = new object[] { new[] { "M" }, new[] { "F" } },
                    Positions = session.Query<Position>().ToList()
                };
            }
            var view = new Ext.Net.MVC.PartialViewResult(containerId, RenderMode.AddTo)
            {
                Model = viewModel
            };
            return view;
        }//end method

        [HttpPost]
        public DirectResult AddEmployee(Employee employee)
        {

            try
            {
                using (var session = SessionFactory.GetNewSession())
                {
                    session.Save(employee);
                    session.Flush();
                }

                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Information,
                                     Title = "Saved successfully",
                                     Html = string.Format("Saved new employee id: {0}", employee.EmployeeId),
                                     AutoHide = true,
                                 }).Show();

            }
            catch (Exception ex)
            {

                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Error,
                                     Title = "Error saving new employee",
                                     Html = ex.Message,
                                     AutoHide = true,
                                 }).Show();

            }

            return this.Direct();
        }

        [HttpDelete]
        public DirectResult DeleteEmployee(int employeeId)
        {
            try
            {

                using (var session = SessionFactory.GetNewSession())
                {
                    session.Delete(new Employee() { EmployeeId = employeeId });
                    session.Flush();
                }
                var store = X.GetCmp<Store>("employeeStore");
                var record = store.GetById(employeeId);
                store.Remove(record);

                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Information,
                                     Title = "Delete successfully",
                                     Html = string.Format("Deleted employee id: {0} from database", employeeId),
                                     AutoHide = true,
                                 }).Show();

            }
            catch (Exception ex)
            {

                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Error,
                                     Title = "Error deleting  employee",
                                     Html = ex.Message,
                                     AutoHide = true,
                                 }).Show();

            }

            return this.Direct();
        }
    }
}

WebAssetManagementMvc/WebAssetManagementMvc/Views/Employee/AddEmployee.cshtml
@using System.Security.Policy
@model WebAssetManagementMvc.Controllers.AddEmployeeViewModel
@{
    var X = Html.X();
}

@(
X.FormPanel()
.Title("เพิ่มรายชื่อพนักงาน")
.Frame(true)
.Width(400)
.Height(300) 
.BodyPadding(13) 
.Margins("5 5 5 0")
.Items( 
    X.FieldSet().Width(350)
    .Title("ข้อมูลพนักงาน")
    .MarginSpec("0 0 0 10")
            .Defaults(d => {
                d.Add(new Parameter("Width", "250"));
                d.Add(new Parameter("LabelWidth", "100"));
            })
.Items( 
    X.TextField()
    .FieldLabel("ชื่อ-นามสกุล")
    .Name("EmployeeName"),

     //Position
     X.ComboBox()
    .FieldLabel("ตำแหน่ง")
    .Name("Position.PositionId")

    .DisplayField("PositionName")
    .ValueField("PositionId")

    .Store( X.Store()
    .ID("positionStore")
    .DataSource(Model.Positions)
    .Model(X.Model() .IDProperty("PositionId").Fields(
                                Html.X().ModelField().Name("PositionId"),
                                Html.X().ModelField().Name("PositionName")
                            ))),
    

     
    X.TextField()
    .FieldLabel("ที่อยู่")
    .Name("Address"),

   
    //Sex
     X.ComboBox()
    .FieldLabel("เพศ")
    .Name("Sex")

    .DisplayField("Gender")
    .ValueField("Gender")

    .Store( X.Store()
    .ID("genderStore")
    .DataSource(Model.Genders)
    .Model(X.Model() .IDProperty("Gender").Fields(
                                Html.X().ModelField().Name("Gender")
                            ))),
 
    
    
    X.TextField()
    .FieldLabel("Username")
    .Name("Username"),
    X.TextField()
    .FieldLabel("Password")
    .Name("Password")

    )
)
.Buttons(X.Button()
                      .Text("เพิ่ม")
                      .DirectClickUrl(Url.Action("AddEmployee","Employee")) )


)

WebAssetManagementMvc/WebAssetManagementMvc/Views/Employee/EmployeeList.cshtml
@{
    var X = Html.X();
}
@(X.GridPanel()
.AnchorHorizontal("100%")
.AnchorVertical("100%")
        .Title("รายการรายชื่อพนักงาน")
        .Store(Html.X().Store()
            .ID("employeeStore")
            .DataSource((object)Model)
            .Model(Html.X().Model()
            
                .IDProperty("EmployeeId")
                .Fields(
                    new ModelField("EmployeeId", ModelFieldType.Int),
                    new ModelField("PositionId", ModelFieldType.Int),
                    new ModelField("PositionName", ModelFieldType.String),
                    new ModelField("EmployeeName", ModelFieldType.String),
                   new ModelField("Address", ModelFieldType.String),
                   new ModelField("Sex", ModelFieldType.String),
        new ModelField("Username", ModelFieldType.String),
        new ModelField("Password", ModelFieldType.String))
        )
        )
        .ColumnModel(
            Html.X().Column().Text("รหัสพนักงาน").DataIndex("EmployeeId").Width(35),
            Html.X().Column().Text("รหัสตำแหน่งพนักงาน").DataIndex("PositionId").Editor(Html.X().NumberField()),
            Html.X().Column().Text("ตำแหน่งพนักงาน").DataIndex("PositionName"),
            Html.X().Column().Text("ชื่อพนักงาน").DataIndex("EmployeeName").Editor(Html.X().TextField()),
            Html.X().Column().ID("address").Text("ที่อยู่").DataIndex("Address").Editor(Html.X().TextField()),
            Html.X().Column().Text("เพศ").DataIndex("Sex").Editor(Html.X().TextField()),
            Html.X().Column().Text("Username").DataIndex("Username").Editor(Html.X().TextField()),
            Html.X().Column().Text("Password").DataIndex("Password").Editor(Html.X().TextField()),
            Html.X().ImageCommandColumn()
                    .Width(30)
                    .Commands(
                        Html.X().ImageCommand()
                            .Icon(Icon.Decline)
                            .ToolTip(t =>
                            {
                                t.Text = "Delete Employee";
                            })
                            .CommandName("deleteEmployee")
                    )
                    .Listeners(l =>
                    {
                        l.Command.Fn = "onGridCellCommand";
                    })
        )//end column model

        .SelectionModel(Html.X().CellSelectionModel())
        .Plugins(Html.X().CellEditing().Listeners(ls => ls.Edit.Fn = "edit").ClicksToEdit(1))
)