WebAssetManagementMvc/WebAssetManagementMvc/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ext.Net;
using Ext.Net.MVC;
using NHibernate.Linq;
using Newtonsoft.Json;
using WebAssetManagementMvc.Helpers;
using WebAssetManagementMvc.Models;
using WebAssetManagementMvc.ViewModels;
using log4net;

namespace WebAssetManagementMvc.Controllers
{
    public class CalendarController : Controller
    {
        private const string DATE_FORMAT = "yyyy-MM-ddTHH:mm:ss";

        private readonly ILog _log = LogManager.GetLogger(typeof(CalendarController).Name);

        public Ext.Net.MVC.PartialViewResult CalendarView(string containerId)
        {
            Ext.Net.X.Head().AddScript("var a =1;");
            var container = X.GetCmp<Container>(containerId);
            container.RemoveAll(true);
            var view = new Ext.Net.MVC.PartialViewResult(containerId, Ext.Net.RenderMode.AddTo);
            return view;
        }




        public ActionResult GetAllEvents()
        {
            using (var session = SessionFactory.GetNewSession())
            {
                try
                {
                    var preventives = session.Query<PlanPreventive>()
                        .ToList()
                        .Select(ev => new CalendarEvent()
                                          {
                                              id = string.Format("PP:{0}", ev.Id),
                                              title = ev.Title,
                                              start = ev.BeginDate,
                                              end = ev.EndDate,
                                              allDay = ev.IsAllDay,
                                              type = "PlanPreventive",
                                              rowId = ev.Id,
                                          });

                    var checkLists = session.Query<PlanCheckList>()
                        .ToList()
                        .Select(ev => new CalendarEvent()
                                          {
                                              id = string.Format("PC:{0}", ev.Id),
                                              title = ev.Title,
                                              start = ev.BeginDate,
                                              end = ev.EndDate,
                                              allDay = ev.IsAllDay,
                                              type = "PlanCheckList",
                                              rowId = ev.Id,
                                          });
                    _log.Debug("data sent back to client");
                    var allEvents = preventives.Concat(checkLists);

                    return new CustomJsonResult(allEvents);
                }
                catch (Exception ex)
                {
                    _log.Error(ex);
                    return Content(ex.Message);
                }

            }
        }


        public Ext.Net.MVC.PartialViewResult ShowAddEventWindow(string containerId)
        {

            var view = new Ext.Net.MVC.PartialViewResult(containerId, RenderMode.RenderTo);


            try
            {
                var beginDate = Request.QueryString["beginDate"].ToDate(DATE_FORMAT);
                var endDate = Request.QueryString["endDate"].ToDate(DATE_FORMAT);
                var isAllDay = Request.QueryString["isAllDay"].ToBoolean();

                var selectedEvent = new CalendarEvent()
                                        {
                                            start = beginDate.Value,
                                            end = endDate,
                                            allDay = isAllDay,
                                        };

                Session["selectedEvent"] = selectedEvent;
                var model = new AddEventViewModel();
                using (var session = SessionFactory.GetNewSession())
                {
                    model.Employees = session.Query<Employee>().ToList();
                    model.Locations = session.Query<Location>().ToList();
                    model.Assets = session.Query<Asset>().ToList();

                    model.Areas = session.Query<Area>().ToList();
                    model.Zones = session.Query<Zone>().ToList();
                    model.Statuses = session.Query<Status>().ToList();
                    model.Materials = session.Query<Material>().ToList();
                }

                view.Model = model;

            }
            catch (Exception ex)
            {
                _log.Error(ex);
            }

            return view;
        }

        public DirectResult LoadSelectedEvent()
        {


            var addPreventiveFormBeginDate = X.GetCmp<TextField>("AddPreventiveFormBeginDate");
            var addPreventiveFormEndDate = X.GetCmp<TextField>("AddPreventiveFormEndDate");
            var addPreventiveFormIsAllDay = X.GetCmp<TextField>("AddPreventiveFormIsAllDay");

            var addCheckListFormBeginDate = X.GetCmp<TextField>("AddCheckListFormBeginDate");
            var addCheckListFormEndDate = X.GetCmp<TextField>("AddCheckListFormEndDate");
            var addCheckListFormIsAllDay = X.GetCmp<TextField>("AddCheckListFormIsAllDay");

            var selectedEvent = (CalendarEvent)Session["selectedEvent"];


            addPreventiveFormBeginDate.SetValue(selectedEvent.start.ToString(DATE_FORMAT));
            addPreventiveFormEndDate.SetValue(selectedEvent.end.Value.ToString(DATE_FORMAT));
            addPreventiveFormIsAllDay.SetValue(selectedEvent.allDay);

            addCheckListFormBeginDate.SetValue(selectedEvent.start.ToString(DATE_FORMAT));
            addCheckListFormEndDate.SetValue(selectedEvent.end.Value.ToString(DATE_FORMAT));
            addCheckListFormIsAllDay.SetValue(selectedEvent.allDay);



            //set value
            return this.Direct();
        }


        [HttpPost]
        public DirectResult AddPlanPreventive(PlanPreventive preventive)
        {
            try
            {

                var beginDate = Request.Form["BeginDate"].ToDate(DATE_FORMAT);
                var endDate = Request.Form["EndDate"].ToDate(DATE_FORMAT);
                var isAllDay = Request.Form["IsAllDay"].ToBoolean();

                preventive.BeginDate = beginDate.Value;
                preventive.EndDate = endDate;
                preventive.IsAllDay = isAllDay;



                using (var session = SessionFactory.GetNewSession())
                {
                    _log.DebugFormat("employeeId: {0}", preventive.Employee.EmployeeId);
                    _log.DebugFormat("locationId: {0}", preventive.Location.LocationId);
                    _log.DebugFormat("zoneId: {0}", preventive.Zone.ZoneId);

                    _log.DebugFormat("assetId: {0}", preventive.Asset.AssetId);
                    _log.DebugFormat("areaId: {0}", preventive.Area.AreaId);
                    _log.DebugFormat("statusId: {0}", preventive.Status.StatusId);
                    _log.DebugFormat("materialId: {0}", preventive.Material.MaterialId);

                    session.Save(preventive);
                    session.Flush();
                }

                //reload all event
                X.AddScript("calendar.fullCalendar( 'refetchEvents');");
                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Information,
                                     Title = "Saved successfully",
                                     Html = string.Format("Saved new Preventive id: {0}", preventive.Id),
                                     AutoHide = true,
                                 }).Show();
            }
            catch (Exception ex)
            {
                X.Msg.Alert("error", "Error adding event, please fill all data and try again.");

                _log.Error(ex);
                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Error,
                                     Title = "Error Preventive new CheckList",
                                     Html = ex.Message,
                                     AutoHide = true,
                                 }).Show();

            }


            return this.Direct();
        }


        [HttpPost]
        public DirectResult AddPlanCheckList(PlanCheckList checkList)
        {
            try
            {

                var beginDate = Request.Form["BeginDate"].ToDate(DATE_FORMAT);
                var endDate = Request.Form["EndDate"].ToDate(DATE_FORMAT);
                var isAllDay = Request.Form["IsAllDay"].ToBoolean();

                checkList.BeginDate = beginDate.Value;
                checkList.EndDate = endDate;
                checkList.IsAllDay = isAllDay;

                using (var session = SessionFactory.GetNewSession())
                {
                    session.Save(checkList);
                    session.Flush();
                }


                //reload all event
                X.AddScript("calendar.fullCalendar( 'refetchEvents');");
                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Information,
                                     Title = "Saved successfully",
                                     Html = string.Format("Saved new CheckList id: {0}", checkList.Id),
                                     AutoHide = true,
                                 }).Show();
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                X.Msg.Alert("error", "error saving CheckList, please fill all data and try again");
                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Error,

WebAssetManagementMvc/WebAssetManagementMvc/Views/Calendar/CalendarView.cshtml
@{
    var X = Html.X();
}



@(
 X.GridPanel().ID("calendar").Width(1000).Height(600)
.Listeners((g) =>
               {
                   g.AfterRender.Fn = "renderCalendar";

               })
      )
@{

    var txtUserName = new TextField()
    {
        FieldLabel = "username",
        Name = "username"
    };

    var txtPassword = new TextField()
    {
        Name = "password",
        FieldLabel = "password",
        InputType = Ext.Net.InputType.Password
    };
}


@(X.Window().ID("addEventWindow").Width(300).Height(250).Title("addEvent")
      .Closable(true)
      .Hidden(true)
      .CloseAction(CloseAction.Hide)
      .Items(
      X.FormPanel().Width(290).Height(200)
      .Items(X.FieldSet().MarginSpec("30 0 0 0").Border(false).Padding(5).Items(txtUserName, txtPassword))
      .Buttons(X.Button().Text("LogIn").DirectClickAction("LogInUser", new { userName = txtUserName.Value })))
)

WebAssetManagementMvc/WebAssetManagementMvc/Views/Calendar/PlanCheckListDetailWindow.cshtml
@model WebAssetManagementMvc.ViewModels.EventDetailViewModel

@{
    var X = Html.X();
    const int HEIGHT = 450;
    const string DATE_FORMAT = "yyyy-MM-ddTHH:mm:ss";
}

@(X.Window()
      .Title("Event Detail")
      .ID("PlanCheckListDetailWindow")
      .CloseAction(CloseAction.Destroy)
      .Width(450)

      .Height(HEIGHT)
      .Icon(Icon.Clock)
      .Layout(LayoutType.Border)
      .Items(

          X.FormPanel()
              .ID("CheckListDetailForm")
              .Title("CheckList")
              .Frame(true)
              .Width(400)
              .Height(HEIGHT)
              .BodyPadding(13)
              .Margins("5 5 5 0")
              .Items(


              //Title
               X.TextField()
                      .FieldLabel("หัวข้องาน")
                      .Name("Title")
                      .Value(Model.PlanCheckList.Title)
                  ,
              
                  X.ComboBox()
                      .FieldLabel("ผู้ตรวจเช็ค")
                      .Name("Employee.EmployeeId")
                      .Value(Model.PlanCheckList.Employee.EmployeeId)

                      .DisplayField("EmployeeName")
                      .ValueField("EmployeeId")
                      .Store(
                          X.Store()
                              .ID("employeeStore")
                              .DataSource(Model.Employees)
                              .Model(
                                  X.Model()
                                      .IDProperty("EmployeeId")
                                      .Fields(
                                          Html.X().ModelField().Name("EmployeeId"),
                                          Html.X().ModelField().Name("EmployeeName")
                                      )
                              )
                      ),

                      //โซน
                    X.ComboBox()
                      .FieldLabel("โซน")
                      .Name("Zone.ZoneId")
                      .Value(Model.PlanCheckList.Zone.ZoneId)

                      .ValueField("ZoneId")
                      .DisplayField("ZoneDetail")

                      .Store(
                          X.Store()
                              .ID("zoneStore")
                              .DataSource(Model.Zones)
                              .Model(
                                  X.Model()
                                      .IDProperty("ZoneId")
                                      .Fields(
                                          Html.X().ModelField().Name("ZoneId"),
                                          Html.X().ModelField().Name("ZoneDetail")
                                      )
                              )),

                              
                  //สถานที่            
                  X.ComboBox()
                      .FieldLabel("สถานที่")
                      .Name("Location.LocationId")
                      .Value(Model.PlanCheckList.Location.LocationId)

                      .DisplayField("Name")
                      .ValueField("LocationId")

                      .Store(
                          X.Store()
                              .ID("locationStore")
                              .DataSource(Model.Locations)
                              .Model(
                                  X.Model()
                                      .IDProperty("LocationId")
                                      .Fields(
                                          Html.X().ModelField().Name("LocationId"),
                                          Html.X().ModelField().Name("Name")
                                      )
                              )
                      ),


                  //พื้นที่    
                  X.ComboBox()
                      .FieldLabel("พื้นที่")
                      .Name("Area.AreaId")
                      .Value(Model.PlanCheckList.Area.AreaId)

                      .DisplayField("AreaId")
                      .ValueField("AreaId")

                      .Store(
                          X.Store()
                              .ID("areaStore")
                              .DataSource(Model.Areas)
                              .Model(
                                  X.Model()
                                      .IDProperty("AreaId")
                                      .Fields(
                                          Html.X().ModelField().Name("AreaId")
                                      )
                              )),

                      
                     //อุปกรณ์        
                      X.ComboBox()
                     .FieldLabel("อุปกรณ์")
                     .Name("Asset.AssetId")

                    .ValueField("AssetId")
                    .DisplayField("AssetName")
                    .Value(Model.PlanCheckList.Asset.AssetId)
                        
                    .Store(
                        X.Store()
                        .ID("assetStore")
                        .DataSource(Model.Assets)
                        .Model(
                            X.Model()
                            .IDProperty("AssetId")
                            .Fields(
                                Html.X().ModelField().Name("AssetId"),
                                Html.X().ModelField().Name("AssetName")
                            )
                        )),
                              
                       //วัสดุ 
                      X.ComboBox()
                      .FieldLabel("วัสดุ")
                      .Name("Material.MaterialId")
                      .Value(Model.PlanCheckList.Material.MaterialId)

                      .ValueField("MaterialId")
                      .DisplayField("MaterialId")

                      .Store(
                          X.Store()
                              .ID("materialStore")
                              .DataSource(Model.Materials)
                              .Model(
                                  X.Model()
                                      .IDProperty("MaterialId")
                                      .Fields(
                                          Html.X().ModelField().Name("MaterialId")
                                      )
                              )),         

                     
                   //สถานะ           
                  X.ComboBox()
                      .FieldLabel("สถานะ")
                      .Name("Status.StatusId")
                      .Value(Model.PlanCheckList.Status.StatusId)

                      .ValueField("StatusId")
                      .DisplayField("StatusName")

                      .Store(
                          X.Store()
                              .ID("statusStore")
                              .DataSource(Model.Statuses)
                              .Model(
                                  X.Model()
                                      .IDProperty("StatusId")
                                      .Fields(
                                          Html.X().ModelField().Name("StatusId"),
                                          Html.X().ModelField().Name("StatusName")
                                      )
                              )),



                  X.TextField()
                      .FieldLabel("วัน/เวลาเริ่มงาน")
                      .Name("BeginDate")
                      .Value(Model.PlanCheckList.BeginDate.ToString(DATE_FORMAT))
                      .ID("AddPreventiveFormBeginDate"),

                  X.TextField()
                      .FieldLabel("วัน/เวลาสิ้นสุดงาน")
                      .Name("EndDate")
                      .Value(Model.PlanCheckList.EndDate.Value.ToString(DATE_FORMAT))
                      .ID("AddPreventiveFormEndDate"),

                  X.TextField()
                      .FieldLabel("งานตลอดวัน")
                      .Name("IsAllDay")
                      .Value(Model.PlanCheckList.IsAllDay)
                      .ID("AddPreventiveFormIsAllDay")
              )
              .Buttons(
              X.Button()
                           .Text("Save")
                           .Icon(Icon.DatabaseSave)
                           .DirectEvents(l =>
                                             {
                                                 l.Click.Url = Url.Action("EditPlanCheckList", "Calendar",
                                                     new { rowId = Model.PlanCheckList.Id });
                                                 l.Click.Method = HttpMethod.PUT;
                                             }
                      ),
                      
              X.Button()
                           .Text("Delete")
                           .Icon(Icon.Delete)
                           .DirectEvents(l =>
                                             {
                                                 l.Click.Url = Url.Action("DeletePlanCheckList", "Calendar",
                                                     new { rowId = Model.PlanCheckList.Id });
                                                 l.Click.Method = HttpMethod.DELETE;
                                             }
                      )

                      )


       )//window
)

WebAssetManagementMvc/WebAssetManagementMvc/Views/Calendar/PlanPreventiveDetailWindow.cshtml
@model WebAssetManagementMvc.ViewModels.EventDetailViewModel

@{
    var X = Html.X();
    const int HEIGHT = 450;
    const string DATE_FORMAT = "yyyy-MM-ddTHH:mm:ss";
}

@(X.Window()
      .Title("Event Detail")
      .ID("PlanPreventiveDetailWindow")
      .CloseAction(CloseAction.Destroy)
      .Width(450)

      .Height(HEIGHT)
      .Icon(Icon.Clock)
      .Layout(LayoutType.Border)
      .Items(

          X.FormPanel()
              .ID("PreventiveDetailForm")
              .Title("Preventive")
              .Frame(true)
              .Width(400)
              .Height(HEIGHT)
              .BodyPadding(13)
              .Margins("5 5 5 0")
              .Items(

              //Title
                X.TextField()
                      .FieldLabel("หัวข้องาน")
                      .Name("Title")
                      .Value(Model.PlanPreventive.Title)
                  ,   
              
               //Employee    
                 X.ComboBox()
                      .FieldLabel("ผู้ตรวจเช็ค")
                      .Name("Employee.EmployeeId")
                      .Value(Model.PlanPreventive.Employee.EmployeeId)

                      .DisplayField("EmployeeName")
                      .ValueField("EmployeeId")
                      .Store(
                          X.Store()
                              .ID("employeeStore")
                              .DataSource(Model.Employees)
                              .Model(
                                  X.Model()
                                      .IDProperty("EmployeeId")
                                      .Fields(
                                          Html.X().ModelField().Name("EmployeeId"),
                                          Html.X().ModelField().Name("EmployeeName")
                                      )
                              )
                      ),

                //Zone
                 X.ComboBox()
                      .FieldLabel("โซน")
                      .Name("Zone.ZoneId")
                      .Value(Model.PlanPreventive.Zone.ZoneId)

                      .ValueField("ZoneId")
                      .DisplayField("ZoneDetail")

                      .Store(
                          X.Store()
                              .ID("zoneStore")
                              .DataSource(Model.Zones)
                              .Model(
                                  X.Model()
                                      .IDProperty("ZoneId")
                                      .Fields(
                                          Html.X().ModelField().Name("ZoneId"),
                                          Html.X().ModelField().Name("ZoneDetail")
                                      )
                              )),
                      
                      
                  //   Location 
                  X.ComboBox()
                      .FieldLabel("สถานที่")
                      .Name("Location.LocationId")
                      .Value(Model.PlanPreventive.Location.LocationId)

                      .DisplayField("Name")
                      .ValueField("LocationId")

                      .Store(
                          X.Store()
                              .ID("locationStore")
                              .DataSource(Model.Locations)
                              .Model(
                                  X.Model()
                                      .IDProperty("LocationId")
                                      .Fields(
                                          Html.X().ModelField().Name("LocationId"),
                                          Html.X().ModelField().Name("Name")
                                      )
                              )
                      ),

                      //Area
                      X.ComboBox()
                      .FieldLabel("พื้นที่")
                      .Name("Area.AreaId")
                      .Value(Model.PlanPreventive.Area.AreaId)

                      .DisplayField("AreaId")
                      .ValueField("AreaId")

                      .Store(
                          X.Store()
                              .ID("areaStore")
                              .DataSource(Model.Areas)
                              .Model(
                                  X.Model()
                                      .IDProperty("AreaId")
                                      .Fields(
                                          Html.X().ModelField().Name("AreaId")
                                      )
                              )),
                      
                      //Asset
                      
                  X.ComboBox()
                      .FieldLabel("อุปกรณ์")
                      .Name("Asset.AssetId")
                      .Value(Model.PlanPreventive.Asset.AssetId)

                      .DisplayField("AssetName")
                      .ValueField("AssetId")

                      .Store(
                          X.Store()
                              .ID("assetStore")
                              .DataSource(Model.Assets)
                              .Model(
                                  X.Model()
                                      .IDProperty("AssetId")
                                      .Fields(
                                          Html.X().ModelField().Name("AssetId"),
                                          Html.X().ModelField().Name("AssetName")
                                      )
                              )),


                  
                    //Material
                        X.ComboBox()
                            .FieldLabel("วัสดุ")
                            .Name("Material.MaterialId")
                            .Value(Model.PlanPreventive.Material.MaterialId)

                            .ValueField("MaterialId")
                            .DisplayField("MaterialId")

                            .Store(
                                  X.Store()
                                      .ID("materialStore")
                                     .DataSource(Model.Materials)
                                    .Model(
                                         X.Model()
                                      .IDProperty("MaterialId")
                                      .Fields(
                                          Html.X().ModelField().Name("MaterialId")
                                      )
                              )),
                  

                    //status
                    
                  X.ComboBox()
                      .FieldLabel("สถานะ")
                      .Name("Status.StatusId")
                      .Value(Model.PlanPreventive.Status.StatusId)

                      .ValueField("StatusId")
                      .DisplayField("StatusName")

                      .Store(
                          X.Store()
                              .ID("statusStore")
                              .DataSource(Model.Statuses)
                              .Model(
                                  X.Model()
                                      .IDProperty("StatusId")
                                      .Fields(
                                          Html.X().ModelField().Name("StatusId"),
                                          Html.X().ModelField().Name("StatusName")
                                      )
                              )),

          

                  //X.TextField()
                  //    .FieldLabel("Detail")
                  //    .Name("Detail")
                  //    .Value(Model.PlanPreventive.Detail),



                  X.TextField()
                      .FieldLabel("วัน/เวลาเริ่มงาน")
                      .Name("BeginDate")
                      .Value(Model.PlanPreventive.BeginDate.ToString(DATE_FORMAT))
                      .ID("AddPreventiveFormBeginDate"),

                  X.TextField()
                      .FieldLabel("วัน/เวลาสิ้นสุดงาน")
                      .Name("EndDate")
                      .Value(Model.PlanPreventive.EndDate.Value.ToString(DATE_FORMAT))
                      .ID("AddPreventiveFormEndDate"),

                  X.TextField()
                      .FieldLabel("งานตลอดวัน")
                      .Name("IsAllDay")
                      .Value(Model.PlanPreventive.IsAllDay)
                      .ID("AddPreventiveFormIsAllDay")
              )
              .Buttons(
              X.Button()
                           .Text("Save")
                           .Icon(Icon.DatabaseSave)
                           .DirectEvents(l =>
                                             {
                                                 l.Click.Url = Url.Action("EditPlanPreventive", "Calendar",
                                                     new { rowId = Model.PlanPreventive.Id });
                                                 l.Click.Method = HttpMethod.PUT;
                                             }
                      ),
                      
              X.Button()
                           .Text("Delete")
                           .Icon(Icon.Delete)
                           .DirectEvents(l =>
                                             {
                                                 l.Click.Url = Url.Action("DeletePlanPreventive", "Calendar",
                                                     new { rowId = Model.PlanPreventive.Id });
                                                 l.Click.Method = HttpMethod.DELETE;
                                             }
                      )

                      )


       )//window
)