WebAssetManagementMvc/WebAssetManagementMvc/Models/NotifyBreakDown.cs
using System;

namespace WebAssetManagementMvc.Models
{
    public class NotifyBreakDown
    {
        public virtual int Id { get; set; }
        public virtual string Title { get; set; }
        public virtual Material Material { get; set; }
        public virtual Asset Asset { get; set; }

        public virtual Zone Zone { get; set; }
        public virtual Location Location { get; set; }
        public virtual Area Area { get; set; }
        public virtual string SymptomBefore { get; set; }
        public virtual Employee EmployeeInformant { get; set; }

        public virtual string SymptomAfter { get; set; }
        public virtual Employee EmployeeBearer { get; set; }
        public virtual Status Status { get; set; }
        public virtual DateTime NotifyDate { get; set; }
        public virtual DateTime? MaintenanceDate { get; set; }
        public virtual string FormState { get; set; }

    }
}

WebAssetManagementMvc/WebAssetManagementMvc/Controllers/NotifyBreakDownController.cs
using System;
using System.Collections;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Ext.Net;
using Ext.Net.MVC;
using NHibernate.Linq;
using Newtonsoft.Json;
using WebAssetManagementMvc.Helpers;
using WebAssetManagementMvc.Models;
using log4net;
using Position = WebAssetManagementMvc.Models.Position;


namespace WebAssetManagementMvc.Controllers
{
    public class NotifyBreakDownController : Controller
    {
        private ILog _log = LogManager.GetLogger(typeof(NotifyBreakDownController).Name);

        private const string DATE_FORMAT = "dd-MM-yyyy HH:mm:ss";

        public NotifyBreakDownController()
        {
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");

        }

        [HttpGet]
        public ActionResult AddNotifyBreakDown(string containerId)
        {
            var container = X.GetCmp<Container>(containerId);
            container.RemoveAll(true);
            var view = new Ext.Net.MVC.PartialViewResult(containerId, RenderMode.AddTo);
            try
            {
                AddNotifyBreakDownViewModel model;
                using (var session = SessionFactory.GetNewSession())
                {

                    model = new AddNotifyBreakDownViewModel()
                    {
                        Areas = session.Query<Area>().ToList(),
                        Assets = session.Query<Asset>().ToList(),
                        Employees = session.Query<Employee>().ToList(),
                        Locations = session.Query<Location>().ToList(),
                        Materials = session.Query<Material>().ToList(),
                        Statuses = session.Query<Status>().ToList(),
                        Zones = session.Query<Zone>().ToList(),
                    };

                    view.Model = model;
                }


            }
            catch (Exception ex)
            {
                _log.Error(ex);
            }
            return view;
        }


        [HttpPost]
        public ActionResult AddNotifyBreakDown(NotifyBreakDown notifyBreakDown)
        {
            try
            {

                var notifyDate = Request.Form["NotifyDate"].ToDate(DATE_FORMAT);
                notifyBreakDown.NotifyDate = notifyDate.Value;

                using (var session = SessionFactory.GetNewSession())
                {
                    _log.DebugFormat("notifyBreakDown.Material.MaterialId: {0}", notifyBreakDown.Material.MaterialId);
                    _log.DebugFormat("notifyBreakDown.Asset.AssetId: {0}", notifyBreakDown.Asset.AssetId);
                    _log.DebugFormat("notifyBreakDown.Zone.ZoneId: {0}", notifyBreakDown.Zone.ZoneId);
                    _log.DebugFormat("notifyBreakDown.Location.LocationId: {0}", notifyBreakDown.Location.LocationId);
                    _log.DebugFormat("notifyBreakDown.Area.AreaId: {0}", notifyBreakDown.Area.AreaId);
                    _log.DebugFormat("notifyBreakDown.EmployeeInformant.EmployeeId: {0}", notifyBreakDown.EmployeeInformant.EmployeeId);

                    session.Save(notifyBreakDown);
                    session.Flush();
                }

                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Information,
                                     Title = "Saved successfully",
                                     Html = string.Format("Saved new NotifyBreakDown id: {0}", notifyBreakDown.Id),
                                     AutoHide = true,
                                 }).Show();

            }
            catch (Exception ex)
            {
                _log.Error(ex);
                X.Msg.Notify(new NotificationConfig
                                 {
                                     Icon = Icon.Error,
                                     Title = "Error",
                                     Html = ex.Message,
                                     AutoHide = true,
                                 }).Show();


            }


            return this.Direct();
        }


        [HttpGet]
        public ActionResult NotifyBreakDownList(string containerId)
        {
            var container = X.GetCmp<Container>(containerId);
            container.RemoveAll(true);
            var view = new Ext.Net.MVC.PartialViewResult(containerId, RenderMode.AddTo);

            try
            {

                NotifyBreakDownListViewModel model;
                using (var session = SessionFactory.GetNewSession())
                {

                    model =
                        new NotifyBreakDownListViewModel()
                        {
                            Areas = session.Query<Area>().ToList(),
                            Assets = session.Query<Asset>().ToList(),
                            Employees = session.Query<Employee>().ToList(),
                            Locations = session.Query<Location>().ToList(),
                            Materials = session.Query<Material>().ToList(),
                            Statuses = session.Query<Status>().ToList(),
                            Zones = session.Query<Zone>().ToList(),

                            NotifyBreakDowns = session.Query<NotifyBreakDown>()
                            .Select(n => new NotifyBreakDonwListRecordViewModel()
                            {
                                AreaName = n.Area.Detail,
                                AssetName = n.Asset.AssetName,
                                EmployeeInformantName = n.EmployeeInformant.EmployeeName,
                                EmployeeBearerId = n.EmployeeBearer != null ? n.EmployeeBearer.EmployeeId : 0,
                                EmployeeBearerName = n.EmployeeBearer != null ? n.EmployeeBearer.EmployeeName : "",
                                Id = n.Id,
                                LocationName = n.Location.Name,
                                MaintenanceDate = n.MaintenanceDate.HasValue ? n.MaintenanceDate.Value.ToString(DATE_FORMAT) : "",
                                MaterialName = n.Material.MaterialId,
                                NotifyDate = n.NotifyDate.ToString(DATE_FORMAT),
                                StatusId = n.Status.StatusId,
                                StatusName = n.Status.StatusName,
                                SymptomAfter = string.IsNullOrEmpty(n.SymptomAfter) ? "" : n.SymptomAfter,
                                SymptomBefore = n.SymptomBefore,
                                Title = n.Title,
                                ZoneName = n.Zone.ZoneDetail,
                            }).ToList()
                        };
                    //for drop down
                    model.Employees.Add(new Employee() { EmployeeId = 0, EmployeeName = "", Position = new Position()});


                    _log.DebugFormat("Area count: {0}", model.Areas.Count());
                    _log.DebugFormat("Asset count: {0}", model.Assets.Count());
                    _log.DebugFormat("Employee count: {0}", model.Employees.Count());

                    _log.DebugFormat("Location count: {0}", model.Locations.Count());
                    _log.DebugFormat("Material count: {0}", model.Materials.Count());
                    _log.DebugFormat("Status count: {0}", model.Statuses.Count());
                    _log.DebugFormat("Zone count: {0}", model.Zones.Count());

                    view.Model = model;
                    return view;
                }

            }
            catch (Exception ex)
            {
                _log.Error(ex);

                return view;
            }

        }


        [HttpGet]
        public ActionResult NotifyBreakDownHistoryList(string containerId)
        {
            var container = X.GetCmp<Container>(containerId);
            container.RemoveAll(true);
            var view = new Ext.Net.MVC.PartialViewResult(containerId, RenderMode.AddTo);

            try
            {

                NotifyBreakDownListViewModel model;
                using (var session = SessionFactory.GetNewSession())
                {

                    model =
                        new NotifyBreakDownListViewModel()
                        {
                            Areas = session.Query<Area>().ToList(),
                            Assets = session.Query<Asset>().ToList(),
                            Employees = session.Query<Employee>().ToList(),
                            Locations = session.Query<Location>().ToList(),
                            Materials = session.Query<Material>().ToList(),
                            Statuses = session.Query<Status>().ToList(),
                            Zones = session.Query<Zone>().ToList(),
                            NotifyBreakDowns = session.Query<NotifyBreakDown>()
                            .Select(n => new NotifyBreakDonwListRecordViewModel()
                            {
                                AreaName = n.Area.Detail,
                                AssetName = n.Asset.AssetName,
                                EmployeeInformantName = n.EmployeeInformant.EmployeeName,
                                EmployeeBearerId = n.EmployeeBearer != null ? n.EmployeeBearer.EmployeeId : 0,
                                EmployeeBearerName = n.EmployeeBearer != null ? n.EmployeeBearer.EmployeeName : "",
                                Id = n.Id,
                                LocationName = n.Location.Name,
                                //default to now
                                MaintenanceDate = n.MaintenanceDate.HasValue ?
                                n.MaintenanceDate.Value.ToString(DATE_FORMAT) : DateTime.Now.ToString(DATE_FORMAT),
                                MaterialName = n.Material.MaterialId,
                                NotifyDate = n.NotifyDate.ToString(DATE_FORMAT),
                                StatusId = n.Status.StatusId,

WebAssetManagementMvc/WebAssetManagementMvc/Views/NotifyBreakDown/AddNotifyBreakDown.cshtml
@using System.Threading
@model WebAssetManagementMvc.Controllers.AddNotifyBreakDownViewModel
@{
    var X = Html.X();
    const int HEIGHT = 450;
    const string DATE_FORMAT = "dd-MM-yyyy HH:mm:ss";

    Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");
    var now = DateTime.Now.ToString(DATE_FORMAT);
}

@(
          X.FormPanel()
              .ID("AddNotifyBreakDownForm")
              .Title("แจ้งซ่อมอุปกรณ์ Break Down")
              .Frame(true)
              .Width(400)
              .Height(HEIGHT)
              .BodyPadding(13)
              .Margins("5 5 5 0")
              .Items( 

                       X.TextField()
                      .FieldLabel("หัวข้องาน")
                      .Name("Title"),

                   @*material *@ 
                   X.ComboBox()
                      .FieldLabel("วัสดุ")
                      .Name("Material.MaterialId")

                      .ValueField("MaterialId")
                      .DisplayField("MaterialId")

                      .Store(
                          X.Store()
                              .ID("materialStore")
                              .DataSource(Model.Materials)
                              .Model(
                                  X.Model()
                                      .IDProperty("MaterialId")
                                      .Fields(
                                          Html.X().ModelField().Name("MaterialId")
                                      )
                              )),
              
                   X.ComboBox()
                      .FieldLabel("อุปกรณ์")
                      .Name("Asset.AssetId")

                      .ValueField("AssetId")
                      .DisplayField("AssetName")

                      .Store(
                          X.Store()
                              .ID("assetStore")
                              .DataSource(Model.Assets)
                              .Model(
                                  X.Model()
                                      .IDProperty("AssetId")
                                      .Fields(
                                          Html.X().ModelField().Name("AssetId"),
                                          Html.X().ModelField().Name("AssetName")
                                      )
                              )),

                              
                  X.ComboBox()
                      .FieldLabel("โซน")
                      .Name("Zone.ZoneId")

                      .ValueField("ZoneId")
                      .DisplayField("ZoneDetail")
                      .Store(
                          X.Store()
                              .ID("zoneStore")
                              .DataSource(Model.Zones)
                              .Model(
                                  X.Model()
                                      .IDProperty("ZoneId")
                                      .Fields(
                                          Html.X().ModelField().Name("ZoneId"),
                                          Html.X().ModelField().Name("ZoneDetail")
                                      )
                              )),

                              
                              
                       X.ComboBox()
                      .FieldLabel("สถานที่")
                      .Name("Location.LocationId")
                      .DisplayField("Name")
                      .ValueField("LocationId")

                      .Store(
                          X.Store()
                              .ID("locationStore")
                              .DataSource(Model.Locations)
                              .Model(
                                  X.Model()
                                      .IDProperty("LocationId")
                                      .Fields(
                                          Html.X().ModelField().Name("LocationId"),
                                          Html.X().ModelField().Name("Name")
                                      )
                              )
                      ),

                              
                      
                  X.ComboBox()
                      .FieldLabel("พื้นที่")
                      .Name("Area.AreaId")
                      .DisplayField("AreaId")
                      .ValueField("AreaId")

                      .Store(
                          X.Store()
                              .ID("areaStore")
                              .DataSource(Model.Areas)
                              .Model(
                                  X.Model()
                                      .IDProperty("AreaId")
                                      .Fields(
                                          Html.X().ModelField().Name("AreaId")
                                      )
                              )),
                      
                              
                       X.TextField()
                      .FieldLabel("อาการที่เสีย")
                      .Name("SymptomBefore"),
                              
                       X.ComboBox()
                      .FieldLabel("ผู้แจ้ง")
                      .Name("EmployeeInformant.EmployeeId")

                      .DisplayField("EmployeeName")
                      .ValueField("EmployeeId")
                      .Store(
                          X.Store()
                              .ID("employeeStore")
                              .DataSource(Model.Employees.Where(e =>e.Position.PositionId == 3))
                              .Model(
                                  X.Model()
                                      .IDProperty("EmployeeId")
                                      .Fields(
                                          Html.X().ModelField().Name("EmployeeId"),
                                          Html.X().ModelField().Name("EmployeeName")
                                      )
                              )
                      ),

                      X.TextField()
                       .FieldLabel("วัน/เวลาที่แจ้งซ่อม")
                       .Name("NotifyDate")
                       .Value(now),

                  X.ComboBox()
                      .FieldLabel("สถานะ")
                      .Name("Status.StatusId")
                      .Value(1)

                      .ValueField("StatusId")
                      .DisplayField("StatusName")

                      .Store(
                          X.Store()
                              .ID("statusStore")
                              .DataSource(Model.Statuses)
                              .Model(
                                  X.Model()
                                      .IDProperty("StatusId")
                                      .Fields(
                                          Html.X().ModelField().Name("StatusId"),
                                          Html.X().ModelField().Name("StatusName")
                                      )
                              ))


              )
              .Buttons(
              X.Button()
                           .Text("เพิ่ม")
                           .Icon(Icon.Add)
                           .DirectEvents(l =>
                                             {
                                                 l.Click.Method = HttpMethod.POST;
                                                 l.Click.Url = Url.Action("AddNotifyBreakDown", "NotifyBreakDown");
                                             })

                )
)

WebAssetManagementMvc/WebAssetManagementMvc/Views/NotifyBreakDown/NotifyBreakDownHistoryList.cshtml
@model WebAssetManagementMvc.Controllers.NotifyBreakDownListViewModel

@{
    var X = Html.X();
}

@(Html.X().GridPanel()
      .Width(900)
      .Height(500)
      .AutoScroll(true)

      .Title("อุปกรณ์แจ้งซ่อม Break Down")
      .Store(Html.X().Store()
                 .ID("notifyBreakDownStore")
                 .DataSource(Model.NotifyBreakDowns)
                 .Model(Html.X().Model()

                            .IDProperty("Id")
                            .Fields(

                                new ModelField("Id", ModelFieldType.Int),
                                new ModelField("Title", ModelFieldType.String),
                                new ModelField("MaterialName", ModelFieldType.String),
                                new ModelField("AssetName", ModelFieldType.String),
                                new ModelField("ZoneName", ModelFieldType.String),
                                new ModelField("LocationName", ModelFieldType.String),
                                new ModelField("AreaName", ModelFieldType.String),
                                new ModelField("SymptomBefore", ModelFieldType.String),
                                new ModelField("EmployeeInformantName", ModelFieldType.String),

                                new ModelField("EmployeeBearerId", ModelFieldType.Int),
                                new ModelField("EmployeeBearerName", ModelFieldType.String),
                                new ModelField("SymptomAfter", ModelFieldType.String),


                                new ModelField("StatusName", ModelFieldType.String),
                                new ModelField("StatusId", ModelFieldType.Int),
                                new ModelField("NotifyDate", ModelFieldType.String),

                                new ModelField("MaintenanceDate", ModelFieldType.String)
                            )))//end store

      .ColumnModel(
          Html.X().Column().Text("ลำดับที่").DataIndex("Id").Width(35),
          Html.X().Column().Text("หัวข้องาน").DataIndex("Title").Width(50),

          Html.X().Column().Text("ผู้แจ้ง").DataIndex("EmployeeInformantName"),

          Html.X().Column().Text("อาการที่เสีย").DataIndex("SymptomBefore"),

          Html.X().Column().Text("ผู้รับแจ้ง").DataIndex("EmployeeBearerName"),
          Html.X().Column().Text("อาการหลังจากแก้ไข").DataIndex("SymptomAfter")
          .Editor(X.TextField().Name("SymptomAfter")),

          
          Html.X().Column().Text("สถานะ").DataIndex("StatusId")
         .Renderer("notifyBreakDownListStatusRenderer")
          .Editor(X.ComboBox()
                      .Name("StatusId")
                      .DisplayField("StatusName")
                      .ValueField("StatusId")
                      .Store(
                          X.Store()
                              .ID("statusStore")
                              .DataSource(Model.Statuses)
                              .Model(
                                  X.Model()
                                      .IDProperty("StatusId")
                                      .Fields(
                                          Html.X().ModelField().Name("StatusId"),
                                          Html.X().ModelField().Name("StatusName")
                                      )
                              )
          )),

          Html.X().Column().Text("วัสดุ").DataIndex("MaterialName"),
          Html.X().Column().Text("อุปกรณ์").DataIndex("AssetName"),
          Html.X().Column().Text("โซน").DataIndex("ZoneName"),
          Html.X().Column().Text("สถานที่").DataIndex("LocationName"),
          Html.X().Column().Text("พื้นที่").DataIndex("AreaName"),
          Html.X().Column().Text("วันที่แจ้งซ่อม").DataIndex("NotifyDate"),

          Html.X().Column().Text("วันที่ซ่อม").DataIndex("MaintenanceDate"),

          Html.X().ImageCommandColumn().Width(100).Text("Export")
          .Commands(
            X.ImageCommand().Icon(Icon.ReportGo).CommandName("exportFillableNotifyBreakDown").Text("export")
              ).Listeners(l =>
              {
                  l.Command.Fn = "onGridCellCommand";
              })
      )//end column model

      .SelectionModel(Html.X().CellSelectionModel())
      .Plugins(Html.X().CellEditing().ClicksToEdit(1).Listeners(
        c => {
            c.Edit.Fn = "editNotifyBreakDown";
        }))

)
      

WebAssetManagementMvc/WebAssetManagementMvc/Views/NotifyBreakDown/NotifyBreakDownList.cshtml
@model WebAssetManagementMvc.Controllers.NotifyBreakDownListViewModel

@{
    var X = Html.X();
}

@(Html.X().GridPanel()
      .Width(900)
      .Height(500)
      .AutoScroll(true)

      .Title("อุปกรณ์แจ้งซ่อม Break Down")
      .Store(Html.X().Store()
                 .ID("notifyBreakDownStore")
                 .DataSource(Model.NotifyBreakDowns)
                 .Model(Html.X().Model()

                            .IDProperty("Id")
                            .Fields(

                                new ModelField("Id", ModelFieldType.Int),
                                new ModelField("Title", ModelFieldType.String),
                                new ModelField("MaterialName", ModelFieldType.String),
                                new ModelField("AssetName", ModelFieldType.String),
                                new ModelField("ZoneName", ModelFieldType.String),
                                new ModelField("LocationName", ModelFieldType.String),
                                new ModelField("AreaName", ModelFieldType.String),
                                new ModelField("SymptomBefore", ModelFieldType.String),
                                new ModelField("EmployeeInformantName", ModelFieldType.String),

                                new ModelField("SymptomAfter", ModelFieldType.String),
                                new ModelField("EmployeeBearerId", ModelFieldType.Int),
                                new ModelField("EmployeeBearerName", ModelFieldType.String),

                                new ModelField("StatusName", ModelFieldType.String),
                                new ModelField("StatusId", ModelFieldType.Int),
                                new ModelField("NotifyDate", ModelFieldType.String),

                                new ModelField("MaintenanceDate", ModelFieldType.String)
                            )))//end store

      .ColumnModel(
          Html.X().Column().Text("ลำดับที่").DataIndex("Id").Width(35),
          Html.X().Column().Text("หัวข้องาน").DataIndex("Title").Width(50),
          Html.X().Column().Text("ผู้แจ้งซ่อม").DataIndex("EmployeeInformantName"),
          Html.X().Column().Text("อาการที่เสีย").DataIndex("SymptomBefore"),

          Html.X().Column().Text("ผู้รับแจ้งซ่อม").DataIndex("EmployeeBearerId")
         .Renderer("notifyBreakDownListEmployeeBearerNameRenderer")
          .Editor(X.ComboBox()
                      .ValueField("EmployeeId")
                      .DisplayField("EmployeeName")
                      .EmptyText("กรุณาเลือกชื่อพนักงาน")
                      .Store(
                          X.Store()
                              .ID("employeeStore")
                              .DataSource(Model.Employees.Where(e =>e.Position.PositionId == 2))
                              .Model(
                                  X.Model()
                                      .IDProperty("EmployeeId")
                                      .Fields(
                                          Html.X().ModelField().Name("EmployeeId"),
                                          Html.X().ModelField().Name("EmployeeName")
                                      )
                              )
          )),

         // Html.X().Column().ID("SymptomAfter").Text("อาการหลังซ่อม").DataIndex("SymptomAfter")
        // .Editor(X.TextField()),

          Html.X().Column().Text("สถานะ").DataIndex("StatusId")
         .Renderer("notifyBreakDownListStatusRenderer")
          .Editor(X.ComboBox()
                      .Name("StatusId")
                      .DisplayField("StatusName")
                      .ValueField("StatusId")
                      .Store(
                          X.Store()
                              .ID("statusStore")
                              .DataSource(Model.Statuses)
                              .Model(
                                  X.Model()
                                      .IDProperty("StatusId")
                                      .Fields(
                                          Html.X().ModelField().Name("StatusId"),
                                          Html.X().ModelField().Name("StatusName")
                                      )
                              )
          ))
          ,
          Html.X().Column().Text("วัสดุ").DataIndex("MaterialName"),
          Html.X().Column().Text("อุปกรณ์").DataIndex("AssetName"),
          Html.X().Column().Text("โซน").DataIndex("ZoneName"),
          Html.X().Column().Text("สถานที่").DataIndex("LocationName"),
          Html.X().Column().Text("พื้นที่").DataIndex("AreaName"),

          Html.X().Column().Text("วันที่แจ้งซ่อม").DataIndex("NotifyDate"),

          Html.X().ImageCommandColumn().Width(100).Text("แบบฟอร์มตรวจเช็ค/ซ่อมบำรุง")
          .Commands(

            X.ImageCommand().Icon(Icon.ReportGo).CommandName("exportNotifyBreakDown").Text("export")

          ).Listeners(l=>l.Command.Fn ="onGridCellCommand")
          


      )//end column model

      .SelectionModel(Html.X().CellSelectionModel())
      .Plugins(Html.X().CellEditing().ClicksToEdit(1).Listeners(c => c.Edit.Fn = "editNotifyBreakDown"))
                                                       
)
      